### ISSUE TITLE
Oracle Text requires line breaks

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarenaCardBuilder#2]
ScriptBuilder is currently removing line breaks to allow the Card Explorer to display oracle without line-breaks.

CardBuilder will require these line-breaks for layout.

If Card Explorer can replace the line-breaks instead, this would allow for layout as per Oracle.

**Comment by lodici** [comment]
I think it would be better in the short term to try and avoid impacting Magarena. If further down the road it becomes a necessity in order to integrate CardBuilder then we can do that then.

However, I don't think there is anything stopping us updating ScriptsBuilder to include any info required by CardBuilder. So just add another property to the script file with the line breaks (eg ``cb.oracle=``, ``cb.layout=``, etc). It should be easier now since I have refactored the messy constructor in CardData into separate calls. If it is necessary to hide the ``cb`` fields for scripts destined for Magarena then we can use something like ``-DcardBuilder=true`` to include/exclude those fields.

**Comment by ShawnieBoy** [comment]
Oh I wouldn't be doing anything that drastic - Just wanted to put something up on here to remember/consider. Keeping this well out of the way of Magarena.

Though saying that there's another part of me that's wondering about the reverse-engineering of the Magarena abilities back into text. Cards can gain and lose abilities so the oracle may not be the best place to get current card information during a game. (But enough of that).

I hadn't even considered a cardBuilder-ized run of the scriptBuilder. That will be very useful for testing things.

Pulling the framelayout etc. is certainly on the cards (ba-dum-tssh), however, just getting a basic format sorted first :grinning:

**Comment by ShawnieBoy** [comment]
This issue was moved to lodici/magarena-cardbuilder#2
