### ISSUE TITLE
Enable Non-int power/toughness

### ISSUE THREAD

**Issue by ShawnieBoy** [magarena/magarenaCardBuilder#5]
A question for you @melvinzhang in a more appropriate place.

How does MagicCardDefinition deal with non-integer power/toughness as in `*/*` or` 2+*/2+*` etc?

**Comment by melvinzhang** [comment]
It treats anything with a * in it as 0.

**Comment by ShawnieBoy** [comment]
That may be a bit tricky from a cardBuilder perspective, as it will be trying to get it's 'out of game' state.

**Comment by ShawnieBoy** [comment]
I guess it would have to go back to the card script itself

**Comment by melvinzhang** [comment]
Anything with * is accompanied by a MagicCDA. The card builder should show the current numerical value.

**Comment by ShawnieBoy** [comment]
Which is fine in a game situation, but in the Card Explorer/Deck editor, the value will show '0' instead.

**Comment by lodici** [comment]
I think, initially anyway, the CardBuilder should concentrate on returning the vanilla card image which means MagicCardDefinition is your only friend (MagicCard only exists in-game).

**Comment by ShawnieBoy** [comment]
But this is an 'issue' with MagicCardDefinition - it won't be able to return a vanilla non-int power/toughness.

**Comment by lodici** [comment]
Why?

**Comment by ShawnieBoy** [comment]
>It treats anything with a * in it as 0.

**Comment by ShawnieBoy** [comment]
It's only a minor thing - was just curious what it did with it

**Comment by lodici** [comment]
Question : does the script file have P/T in the correct format?

**Comment by ShawnieBoy** [comment]
Yeah, looks like it will become the new source, 
if power or toughness = 0, check script file and compare

**Comment by lodici** [comment]
Or why not just store the unreconstructed script value in a new field in MagicCardDefintion (eg.``ptLabel``) when you load the script?

**Comment by ShawnieBoy** [comment]
cardBuilder isn't loading scripts at the moment, it's taking information from MagicCards and MagicCardDefinitions, but it's a thought.

**Comment by lodici** [comment]
CardBuilder should have no knowledge of scripts and should be able to build an image given a MagicCardDefinition. It is Magarena's job to make sure MagicCardDefinition has all the info that CardBuilder needs. While developing CardBuilder if MagicCardDefinition does not have the info required then add a field so that it does. As you are using an external JAR you should create a new class that extends MagicCardDefinition into which you can add the additional fields/methods as required.

**Comment by ShawnieBoy** [comment]
:+1:  Good point.

**Comment by lodici** [comment]
The thing to remember is that MagicCardDefinition is the internal representation of a script file which in turn is based on info extracted from the json data feed. You need to make sure that all the data you need to draw a replica card image is available from the feed even if it is not currently present in the script file.

**Comment by lodici** [comment]
I can see now that you plan on using this to update card images in-game through MagicCard.

I think that means there are two distinct goals to CardBuilder. The first which will have the smallest impact on Magarena is the generation of the vanilla card replica image. Magarena will give CardBuilder a MagicCardDefinition and CardBuilder returns a bufferedImage. This is a drop-in replacement for the current mechanism which basically loads the bufferedimage from the images directory.

The second goal which will potentially be much more disruptive is the generation of the card image using MagicCard so that it can reflect the state of the card in game. This will not be a drop-in replacement and we will also need to consider how images are managed and cached for optimium performance and resource usage.

I think the first goal should be the main priority.

**Comment by ShawnieBoy** [comment]
Some good points there @lodici 

I think I would have got to that conclusion eventually as well - woods and trees comes to mind. :smile: 

I've been putting this together with the idea that it would be sat separate, with minimal interaction with Magarena, just returning bufferedImages as it's fed information.Once everything is developed it should slot in quite seamlessly. But I can see now that giving it a 'halfway' milestone of just doing the basics would aid the second half as it actually begins to interact 'for real'

I've already been concerned about performance as I have no idea about the real gritty backbone of resource management, ram useage etc. I'm just trying to make it look right.

An interior designer on a construction site.

I'll put together an Issue showing a more detailed breakdown of what I still need to do, it's still far from ready.

**Comment by melvinzhang** [comment]
For the purpose of rendering cards, I would suggest using a separate interface, say MagicRenderable. It would make it clearer what methods are used and remove the need to couple rendering with a specific class such as MagicCard.

I could see us rendering MagicCardDefinition (rendering outside of games), MagicCard (rendering in game, with pt determined by characteristic defining ability), MagicPermanent (rendering in game, with dynamic properties adjusted by continuous effects). Each of these classes have a lot of methods which are not necessary for the purpose of rendering.

The way I see it, MagicRenderable will have only the minimum methods needs to render the card, get the subtypes, get the types, abilities. etc. To integrate, we can have the concrete classes either implement MagicRenderable or return a MagicRenderable object

**Comment by melvinzhang** [comment]
Currently we cache images by the image filename, moving forward to using rendered images we can construct a hash of the MagicRenderable data and use that as the key. This can be implemented as a static genCacheKey method in the MagicRenderable interface.

When the render gets a new MagicRenderable, it generates the cache key and checks its internal cache. If the image is already there, return it. Otherwise render a new image and store it in the cache tied to the cache key.
